### ISSUE TITLE
Search some possibilities to filter tags in the log messages

### ISSUE THREAD

**Issue by AndrewGavril** [moevm/qemu-riscv-cluster#40]
Disscussion: https://github.com/moevm/qemu-riscv-cluster/pull/28#discussion_r2035266606

**Comment by NiksBrn** [comment]
На данный момент нет возможности динамически добавлять кастомные теги через само приложение, так как мы используем Loki logging driver, который требует статического определения меток (labels) в конфигурации.

Для парсинга тегов из логов предлагаю следующий единый формат: key1=value1 key2=value2 message

На данный момент метки lvl будто достаточно, но при необходимости, парсинг новых меток можно просто внести в конфиг: 
```
loki-pipeline-stages: |
            - regex:
                expression: '(level|lvl|severity)=(?P<level>\w+)'
            - labels:
                level: level
            - regex:
                expression: '(tags|tag|tg)=(?P<tag>\w+)'
            - labels:
                tag: tag
            - regex:
                expression: '(?i)(?P<level>error|warning|warn|err|critical|fail)'
            - labels:
                level: level
```
